# Generated by Django 5.2.4 on 2025-08-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='categorys', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(max_length=200, verbose_name='اسم بازی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('discount', models.SmallIntegerField(blank=True, null=True, verbose_name='تخفیف')),
                ('image', models.ImageField(upload_to='products', verbose_name='عکس')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('popular', models.BooleanField(default=False, verbose_name='محبوب')),
                ('category', models.ManyToManyField(related_name='product', to='product.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
