# Generated by Django 5.2.4 on 2025-08-01 18:42

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل اکانت')),
                ('password', models.CharField(max_length=200, verbose_name='رمز اکانت')),
                ('gameid', models.CharField(max_length=200, verbose_name='ایدی اکانت')),
                ('gamename', models.CharField(blank=True, null=True, verbose_name='اسم اکانت')),
                ('body', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اکانت',
                'verbose_name_plural': 'اکانت ها',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('successful', 'موفق'), ('waiting', 'در حال بررسی'), ('Unsuccessful', 'ناموفق')], default='waiting', max_length=12, verbose_name='وضعیت')),
                ('total_price', models.IntegerField(default=0, verbose_name='جمع قیمت')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='cart.account', verbose_name='اکانت کاربر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=0, verbose_name='تعداد')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت محصول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order', verbose_name='سفارشات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول سبد خرید',
                'verbose_name_plural': 'محصولات سبد خرید',
            },
        ),
    ]
